INSERT INTO country(id, name) VALUES(1,'Portugal');
INSERT INTO country(id, name) VALUES(2,'Spain');

INSERT INTO city(id, name, countryId) VALUES(1,'Aveiro',1);
INSERT INTO city(id, name, countryId) VALUES(2,'Beja',1);
INSERT INTO city(id, name, countryId) VALUES(3,'Braga',1);
INSERT INTO city(id, name, countryId) VALUES(4,'Bragança',1);
INSERT INTO city(id, name, countryId) VALUES(5,'Castelo Branco',1);
INSERT INTO city(id, name, countryId) VALUES(6,'Coimbra',1);
INSERT INTO city(id, name, countryId) VALUES(7,'Évora',1);
INSERT INTO city(id, name, countryId) VALUES(8,'Faro',1);
INSERT INTO city(id, name, countryId) VALUES(9,'Guarda',1);
INSERT INTO city(id, name, countryId) VALUES(10,'Leiria',1);
INSERT INTO city(id, name, countryId) VALUES(11,'Lisboa',1);
INSERT INTO city(id, name, countryId) VALUES(12,'Portalegre',1);
INSERT INTO city(id, name, countryId) VALUES(13,'Porto',1);
INSERT INTO city(id, name, countryId) VALUES(14,'Santarém',1);
INSERT INTO city(id, name, countryId) VALUES(15,'Setúbal',1);
INSERT INTO city(id, name, countryId) VALUES(16,'Viana Do Castelo',1);
INSERT INTO city(id, name, countryId) VALUES(17,'Vila Real',1);
INSERT INTO city(id, name, countryId) VALUES(18,'Viseu',1);
INSERT INTO city(id, name, countryId) VALUES(19,'Angra do Heroísmo',1);
INSERT INTO city(id, name, countryId) VALUES(20,'Funchal',1);
INSERT INTO city(id, name, countryId) VALUES(21,'Ponta Delgada',1);
INSERT INTO city(id, name, countryId) VALUES(22,'Pico',1);
INSERT INTO city(id, name, countryId) VALUES(23,'Flores',1);
INSERT INTO city(id, name, countryId) VALUES(24,'Corvo',1);
INSERT INTO city(id, name, countryId) VALUES(25,'Graciosa',1);

INSERT INTO city(id, name, countryId) VALUES(26,'Andalucía',2);
INSERT INTO city(id, name, countryId) VALUES(27,'Aragón',2);
INSERT INTO city(id, name, countryId) VALUES(28,'Principado de Asturias',2);
INSERT INTO city(id, name, countryId) VALUES(29,'Baleares',2);
INSERT INTO city(id, name, countryId) VALUES(30,'Canarias',2);
INSERT INTO city(id, name, countryId) VALUES(31,'Cantabria',2);
INSERT INTO city(id, name, countryId) VALUES(32,'Castilla-La Mancha',2);
INSERT INTO city(id, name, countryId) VALUES(33,'Castilla y León',2);
INSERT INTO city(id, name, countryId) VALUES(34,'Cataluña',2);
INSERT INTO city(id, name, countryId) VALUES(35,'Extremadura',2);
INSERT INTO city(id, name, countryId) VALUES(36,'Galicia',2);
INSERT INTO city(id, name, countryId) VALUES(37,'La Rioja',2);
INSERT INTO city(id, name, countryId) VALUES(38,'Comunidad de Madrid',2);
INSERT INTO city(id, name, countryId) VALUES(39,'Región de Murcia',2);
INSERT INTO city(id, name, countryId) VALUES(40,'Comunidad Foral de Navarra',2);
INSERT INTO city(id, name, countryId) VALUES(41,'País Vasco',2);
INSERT INTO city(id, name, countryId) VALUES(42,'Comunidad Valenciana',2);
INSERT INTO city(id, name, countryId) VALUES(43,'Ceuta',2);
INSERT INTO city(id, name, countryId) VALUES(44,'Melilla',2);
