INSERT INTO country(name) VALUES('Portugal');
INSERT INTO country(name) VALUES('Spain');

INSERT INTO city(name, countryId) VALUES('Aveiro',1);
INSERT INTO city(name, countryId) VALUES('Beja',1);
INSERT INTO city(name, countryId) VALUES('Braga',1);
INSERT INTO city(name, countryId) VALUES('Bragança',1);
INSERT INTO city(name, countryId) VALUES('Castelo Branco',1);
INSERT INTO city(name, countryId) VALUES('Coimbra',1);
INSERT INTO city(name, countryId) VALUES('Évora',1);
INSERT INTO city(name, countryId) VALUES('Faro',1);
INSERT INTO city(name, countryId) VALUES('Guarda',1);
INSERT INTO city(name, countryId) VALUES('Leiria',1);
INSERT INTO city(name, countryId) VALUES('Lisboa',1);
INSERT INTO city(name, countryId) VALUES('Portalegre',1);
INSERT INTO city(name, countryId) VALUES('Porto',1);
INSERT INTO city(name, countryId) VALUES('Santarém',1);
INSERT INTO city(name, countryId) VALUES('Setúbal',1);
INSERT INTO city(name, countryId) VALUES('Viana Do Castelo',1);
INSERT INTO city(name, countryId) VALUES('Vila Real',1);
INSERT INTO city(name, countryId) VALUES('Viseu',1);
INSERT INTO city(name, countryId) VALUES('Angra do Heroísmo',1);
INSERT INTO city(name, countryId) VALUES('Funchal',1);
INSERT INTO city(name, countryId) VALUES('Ponta Delgada',1);
INSERT INTO city(name, countryId) VALUES('Pico',1);
INSERT INTO city(name, countryId) VALUES('Flores',1);
INSERT INTO city(name, countryId) VALUES('Corvo',1);
INSERT INTO city(name, countryId) VALUES('Graciosa',1);

INSERT INTO city(name, countryId) VALUES('Andalucía',2);
INSERT INTO city(name, countryId) VALUES('Aragón',2);
INSERT INTO city(name, countryId) VALUES('Principado de Asturias',2);
INSERT INTO city(name, countryId) VALUES('Baleares',2);
INSERT INTO city(name, countryId) VALUES('Canarias',2);
INSERT INTO city(name, countryId) VALUES('Cantabria',2);
INSERT INTO city(name, countryId) VALUES('Castilla-La Mancha',2);
INSERT INTO city(name, countryId) VALUES('Castilla y León',2);
INSERT INTO city(name, countryId) VALUES('Cataluña',2);
INSERT INTO city(name, countryId) VALUES('Extremadura',2);
INSERT INTO city(name, countryId) VALUES('Galicia',2);
INSERT INTO city(name, countryId) VALUES('La Rioja',2);
INSERT INTO city(name, countryId) VALUES('Comunidad de Madrid',2);
INSERT INTO city(name, countryId) VALUES('Región de Murcia',2);
INSERT INTO city(name, countryId) VALUES('Comunidad Foral de Navarra',2);
INSERT INTO city(name, countryId) VALUES('País Vasco',2);
INSERT INTO city(name, countryId) VALUES('Comunidad Valenciana',2);
INSERT INTO city(name, countryId) VALUES('Ceuta',2);
INSERT INTO city(name, countryId) VALUES('Melilla',2);
